### ISSUE TITLE
Split the rig

### ISSUE THREAD

**Issue by Nickduino** [nemosminer/NemosMiner-v2.5.2-windows#351]
Hi,

I'd like to mine with 6 cards to a wallet and 6 others to a second wallet. All on one rig.
Am I right to think I could run two instances, one with _-SelGPUDSTM '0 1 2 3 4 5'_ and _-SelGPUCC '0,1,2,3,4,5'_ while the other uses _-SelGPUDSTM '6 7 8 9 10 11'_ and _-SelGPUCC '6,7,8,9,10,11'_?
Alternatively, can I use _-SelGPU will "X Y Z"_ or is it not implemented yet?

Or maybe it's 01, 02, 03, ... rather ant 1, 2, 3 when you use more than 11 cards?

Lastly, what happens if one riser dies? Is the instance of NemosMiner launched with 5 of them? Only one instance works? Everything is fucked and my rig will catch fire?

**Comment by Olegik-ah** [comment]
Hi!
2 or more instances of nemosminer cant run on 1 rig because of miner programs (ccminer, etc) api port binding
If you start nemosminer  with -SelGPUDSTM '0 1 2 3 4 5' and -SelGPUCC '0,1,2,3,4,5' and 1 riser/card will die - whole instance of nemosminer will not work (powershell script will work, but miner programs not...)

**Comment by Nickduino** [comment]
Would it be possible to tell NemosMiner **on which port** it should listen for the miner output?

e.g. one port for the first half, one port for the other?



Or go even further: one miner (so, one port) for every card, so that a card/riser dying won't fuck everything up?
